# Generated by Django 4.2.16 on 2024-09-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='image',
            new_name='image_large',
        ),
        migrations.AddField(
            model_name='card',
            name='image_small',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='is_wanted',
            field=models.BooleanField(default=False),
        ),
    ]
